version: '3.8'

services:
  bonus-service:
    build:
      context: /var/www/bonus-service
      dockerfile: Dockerfile
    container_name: bonus-service
    hostname: bonus-service
    networks:
      - sbenet
    ports:
      - 9002:80
      - 9003:5000
    expose:
      - 80
      - 5000
    environment:
      DB_TYPE: mysql
      DB_HOST: betrader-database-do-user-11619495-0.b.db.ondigitalocean.com
      DB_PORT: 25060
      DB_PASSWORD: AVNS_QzyFKDS7oT4Rcy541Px
      DB_USERNAME: fixture_service
      DB_NAME: bonus_service
      SYSTEM_PORT: 80
      SYSTEM_HOST: 0.0.0.0
      DEBUG: 1
      RABITTMQ_URI: amqp://bs:betting@137.184.222.24:5672/sportsbook
      FEEDS_SERVICE_GRPC_URI: 161.35.104.145:6011
      BETRADAR_API_TOKEN: jITK7nv8awJ5kAgNrW
      GRPC_PORT: 5000
      GRPC_HOST: 0.0.0.0

    deploy:
      restart_policy:
        condition: on-failure
networks:
  sbenet:
    driver: bridge