version: '3.8'

services:
  betting-service:
    build:
      context: /Volumes/www/node/sportsbook/betting-service
      dockerfile: Dockerfile
    container_name: betting-service
    hostname: betting-service
    networks:
      - sbenet
    ports:
      - 9000:80
      - 9001:5000
    expose:
      - 80
      - 5000
    environment:
      DB_TYPE: mysql
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_PASSWORD:
      DB_USERNAME: root
      DB_NAME: betting_service_v1
      SYSTEM_PORT: 80
      SYSTEM_HOST: 0.0.0.0
      DEBUG: 1
      RABITTMQ_URI: amqp://bs:betting@137.184.222.24:5672/sportsbook
      FEEDS_SERVICE_GRPC_URI: 161.35.104.145:6011

    deploy:
      restart_policy:
        condition: on-failure

# Names our volume
volumes:
  db:

networks:
  sbenet:
    driver: bridge